name: Java Build

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
      - run: mvn clean install
